# Specify the build of reference human genome used (either GRCh37 or GRCh38)
BUILD: "GRCh37"

##### Set file directories #####

# links to reference human genome and various vcf annotation databases
GENOME: "/path/to/reference/human/genome/ucsc.hg19.fasta"
dbSNP: "/path/to/dbSNP/All_20180423.vcf.gz"
VEP: "/path/to/vep/GRCh37/"
dbNSFP: "/path/to/dbNSFP/dbNSFPv4.0a.hg19.custombuild.gz"
MILLS: "/path/to/Mills/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz"
INDEL1000G: "/path/to/1000G/indels/1000G_phase1.indels.hg19.sites.vcf.gz"
SNP1000G: "/path/to/1000G/snps/1000G_phase1.snps.high_confidence.hg19.sites.vcf.gz"
OMNI: "/path/to/omni/1000G_omni2.5.hg19.sites.vcf.gz"
HAPMAP: "/path/to/hapmap/hapmap_3.3.hg19.sites.vcf.gz"
CADD: "/path/to/CADD/whole_genome_SNVs.tsv.gz"

##### Configuration #####

# rule: gatk4_VQSR_indel and gatk4_VQSR_SNP
# software: gatk ApplyVQSR. See https://gatk.broadinstitute.org/hc/en-us/articles/360037056912-ApplyVQSR
# parameter: -ts-filter-level
# description: The truth sensitivity level at which to start filtering
SENSITIVITY: "99.0"

# rule 

##### Fixed - don't change #####

# Overall description of the pipeline/workflow
REPORTWORKFLOW: "report/workflow_37.rst"
