# Specify the build of reference genome used (either 'GRCh37' or 'GRCh38')
BUILD: "GRCh37"

# Specify the type of input data (either 'Single' or 'Cohort')
DATA: "Cohort"

# File directories to reference genome, dbSNP database and various vcf annotation databases
REFGENOME: "/path/to/reference/human/genome/ucsc.hg19.fasta"
dbSNP: "/path/to/dbSNP/All_20180423.vcf.gz"
VEP: "/path/to/vep/GRCh37/"
dbNSFP: "/path/to/dbNSFP/dbNSFPv4.0a.hg19.custombuild.gz"
MILLS: "/path/to/Mills/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz"
INDEL1000G: "/path/to/1000G/indels/1000G_phase1.indels.hg19.sites.vcf.gz"
SNP1000G: "/path/to/1000G/snps/1000G_phase1.snps.high_confidence.hg19.sites.vcf.gz"
OMNI: "/path/to/omni/1000G_omni2.5.hg19.sites.vcf.gz"
HAPMAP: "/path/to/hapmap/hapmap_3.3.hg19.sites.vcf.gz"
CADD: "/path/to/CADD/whole_genome_SNVs.tsv.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"

# Whole exome sequencing (WES) specific settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: "-L /path/to/regions/.bed"
  # Amount of padding (in bp) to add to each interval you are including
  PADDING: "-ip 100"

# Resources used to filter indels and SNP's
# Either call resources from databases defined above or provide a file directory
# Additional resources can be added
FILTERING:
  # Single sample analyses
  SINGLE: ""

  # Cohort analyses
  COHORT:
    INDELS: "-resource:mills, known=false, training=true, truth=true, prior=12.0 config['MILLS'])
            -resource:1000G, known=false, training=true, truth=false, prior=10.0 config['INDEL1000G'])
            -resource:dbsnp, known=true, training=false, truth=false, prior=2.0 config['dbSNP'])"
    SNPS: "-resource:hapmap, known=false,training=true,truth=true,prior=15.0 config['HAPMAP'])
          -resource:omni, known=false,training=true,truth=false,prior=12.0 config['OMNI'])
          -resource:1000G, known=false,training=true,truth=false,prior=10.0 config['SNP1000G'])
          -resource:dbsnp, known=true,training=false,truth=false,prior=2.0 config['dbSNP'])"