############################
##### Overall workflow #####
############################

# Build of reference genome (either 'GRCh37' or 'GRCh38')
BUILD: "GRCh38"

# Type of input data (either 'Single' or 'Cohort')
DATA: "Single"

# File directories to reference genome and dbSNP database
REFGENOME: "/path/to/reference/human/genome/Homo_sapiens_assembly38.fasta.gz"
dbSNP: "/path/to/dbSNP/All_20180418.vcf.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"

# WES settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: ""
  # Padding (in bp) to add to each interval
  PADDING: ""

#############################
##### Variant filtering #####
#############################

# Resources used to filter indels and SNP's...
FILTERING:
  # ...for analysis of single samples
  SINGLE: "--resource /path/to/hapmap/hapmap_3.3.hg38.vcf.gz
          --resource /path/to/Mills/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"

  # ...for analysis of cohorts
  COHORT:
    INDELS: ""
    SNPS: ""

##########################
##### VCF annotation #####
##########################

# File directories to vcf annotation databases
VEP: "/path/to/vep/GRCh38/"
dbNSFP: "/path/to/dbNSFP/dbNSFPv4.0a_custombuild.gz"
CADD: "/path/to/CADD/whole_genome_SNVs.tsv.gz"