############################
##### Overall workflow #####
############################

# Build of reference genome (either 'GRCh37' or 'GRCh38')
BUILD: "GRCh38"

# Type of input data (either 'Single' or 'Cohort')
DATA: "Cohort"

# File directories to reference genome and dbSNP database
REFGENOME: "/path/to/reference/human/genome/Homo_sapiens_assembly38.fasta"
dbSNP: "/path/to/dbSNP/All_20180418.vcf.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"

# WES settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: ""
  # Padding (in bp) to add to each interval
  PADDING: ""

#############################
##### Variant filtering #####
#############################

# Resources used to filter indels and SNP's...
FILTERING:
  # ...for analysis of single samples
  SINGLE: ""

  # ...for analysis of cohorts
  COHORT:
    INDELS: "-resource:mills, known=false, training=true, truth=true, prior=12.0 /path/to/Mills/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
            -resource:dbsnp, known=true, training=false, truth=false, prior=2.0 /path/to/dbSNP/All_20180418.vcf.gz"
    SNPS: "-resource:hapmap, known=false,training=true,truth=true,prior=15.0 /path/to/hapmap/hapmap_3.3.hg38.vcf.gz
          -resource:omni, known=false,training=true,truth=false,prior=12.0 /path/to/omni/1000G_omni2.5.hg38.vcf.gz
          -resource:1000G, known=false,training=true,truth=false,prior=10.0 /path/to/1000G/snps/1000G_phase1.snps.high_confidence.hg38.vcf.gz
          -resource:dbsnp, known=true,training=false,truth=false,prior=2.0 /path/to/dbSNP/All_20180418.vcf.gz"

##########################
##### VCF annotation #####
##########################

# File directories to vcf annotation databases
VEP: "/path/to/vep/GRCh38/"
dbNSFP: "/path/to/dbNSFP/dbNSFPv4.0a_custombuild.gz"
CADD: "/path/to/CADD/whole_genome_SNVs.tsv.gz"